clone_depth: 1

only_commits:
  files:
    - src/
    - deps/

before_build:
  - cd C:\projects\lovr
  - git submodule update --init
  - md build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=%configuration% ..

build:
  project: build\lovr.sln
  verbosity: quiet
