skip_branch_with_pr: true

clone_depth: 1

only_commits:
  files:
    - src/
    - deps/

branches:
  only:
    - master

environment:
  VULKAN_SDK: C:/VulkanSDK/1.3.216.0

cache:
  - VulkanSDK.exe

install:
  - if not exist VulkanSDK.exe curl -L --silent --show-error --output VulkanSDK.exe https://sdk.lunarg.com/sdk/download/1.3.216.0/windows/VulkanSDK-1.3.216.0-Installer.exe?Human=true
  - VulkanSDK.exe /S

before_build:
  - cd C:\projects\lovr
  - git submodule update --init
  - md build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=%configuration% -A x64 ..

configuration: Release

build:
  project: build\lovr.sln
  verbosity: quiet

after_build:
  - cd C:\projects\lovr
  - 7z a lovr.zip C:\projects\lovr\build\Release\*.dll C:\projects\lovr\build\Release\lovr.exe

artifacts:
  - path: lovr.zip

deploy:
  provider: Webhook
  url: https://lovr.org/nightly
  on:
    branch: master
  authorization:
    secure: zbxwiHmtJRVP9FdiqxepLdLGjxhtpjVytb+yLSqrz+8Bl1bH6k5Zts809bLrEjzn
